<?php
declare(strict_types=1); namespace Wms;
final class EntityService extends Service {
 public function vehicles(string$a,array$p,array$u):array{if($a==='list')return$this->vehicleList($p);if($a==='create'){if(!Util::text($p['number']??''))throw new ApiException('VALIDATION','Укажите номер автомобиля');$id=Util::uuid();$this->db->exec('INSERT INTO vehicles(id,number,driver,delivery_number,expected_date,status,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)',[$id,strtoupper(Util::text($p['number'])),Util::text($p['driver']??''),Util::text($p['deliveryNumber']??''),$p['expectedDate']?:null,'Грузится в Киеве',Util::now(),$u['id']]);$r=$this->vehicle($id);$this->audit->log($u,'CREATE','vehicle',$id,[],$r);return$r;}if($a==='update')return$this->db->transaction(function()use($p,$u){$old=$this->one('SELECT * FROM vehicles WHERE id=? AND deleted_at IS NULL',[$p['id']??''],'Автомобиль не найден');$status=($p['status']??'')==='Выгружено в Хмельницком'?'Выгружено в Хмельницком':'Грузится в Киеве';$unloaded=$status==='Выгружено в Хмельницком'?($old['unloaded_at']?:Util::now()):null;$this->conflict($this->db->exec('UPDATE vehicles SET number=?,driver=?,delivery_number=?,expected_date=?,status=?,unloaded_at=?,version=version+1 WHERE id=? AND version=?',[strtoupper(Util::text($p['number'])),Util::text($p['driver']??''),Util::text($p['deliveryNumber']??''),$p['expectedDate']?:null,$status,$unloaded,$old['id'],(int)$p['version']]));$this->audit->log($u,'UPDATE','vehicle',$old['id'],$old,$p);return[];});throw new ApiException('ROUTE','Неизвестное действие');}
 private function vehicle(string$id):array{return$this->camel($this->one("SELECT v.*,CONCAT_WS(' ',v.number,v.driver,v.delivery_number,v.status) search_text FROM vehicles v WHERE id=?",[$id]));}
 private function vehicleList(array$p):array{[$page,$size,$offset]=Util::page($p);$where='v.deleted_at IS NULL';$args=[];$search=Util::text($p['search']??'');if($search){$where.=' AND CONCAT_WS(" ",v.number,v.driver,v.delivery_number,v.status) LIKE ?';$args[]="%$search%";}if(!empty($p['status'])){$where.=' AND v.status=?';$args[]=$p['status'];}$total=(int)$this->db->one("SELECT COUNT(*) n FROM vehicles v WHERE $where",$args)['n'];array_push($args,$size,$offset);$rows=$this->db->all("SELECT v.* FROM vehicles v WHERE $where ORDER BY created_at DESC LIMIT ? OFFSET ?",$args);return['items'=>array_map(fn($x)=>$this->camel($x),$rows),'page'=>$page,'pageSize'=>$size,'total'=>$total,'pages'=>(int)ceil($total/$size)];}
 public function deliveries(string$a,array$p,array$u):array{if($a==='list')return$this->deliveryList($p);if($a==='get'){$d=$this->delivery($p['id']??'');return['delivery'=>$d,'prns'=>$this->prnRows('p.delivery_id=?',[$d['id']])];}if($a==='create'){return$this->db->transaction(function()use($p,$u){$number=Util::text($p['number']??'');if(!$number)throw new ApiException('VALIDATION','Укажите номер доставки');if($this->db->one('SELECT id FROM deliveries WHERE number=?',[$number]))throw new ApiException('DUPLICATE','Доставка с таким номером уже существует');$vehicle=$p['vehicleId']??null;if(!$vehicle){$v=$this->db->one('SELECT id FROM vehicles WHERE delivery_number=? AND deleted_at IS NULL LIMIT 1',[$number]);$vehicle=$v['id']??null;}$id=Util::uuid();$this->db->exec('INSERT INTO deliveries(id,number,vehicle_id,created_at,created_by) VALUES(?,?,?,?,?)',[$id,$number,$vehicle?:null,Util::now(),$u['id']]);$r=$this->delivery($id);$this->audit->log($u,'CREATE','delivery',$id,[],$r);return$r;});}throw new ApiException('ROUTE','Неизвестное действие');}
 private function delivery(string$id):array{return$this->camel($this->one("SELECT d.*,v.number vehicle_number,(SELECT COUNT(*) FROM prns p WHERE p.delivery_id=d.id AND p.deleted_at IS NULL) prn_count,'Создана' status FROM deliveries d LEFT JOIN vehicles v ON v.id=d.vehicle_id WHERE d.id=? AND d.deleted_at IS NULL",[$id],'Доставка не найдена'));}
 private function deliveryList(array$p):array{[$page,$size,$offset]=Util::page($p);$q='%'.Util::text($p['search']??'').'%';$total=(int)$this->db->one('SELECT COUNT(*) n FROM deliveries d WHERE d.deleted_at IS NULL AND (?="%%" OR d.number LIKE ?)',[$q,$q])['n'];$rows=$this->db->all("SELECT d.*,v.number vehicle_number,(SELECT COUNT(*) FROM prns p WHERE p.delivery_id=d.id AND p.deleted_at IS NULL) prn_count,'В работе' status FROM deliveries d LEFT JOIN vehicles v ON v.id=d.vehicle_id WHERE d.deleted_at IS NULL AND (?='%%' OR d.number LIKE ?) ORDER BY d.created_at DESC LIMIT ? OFFSET ?",[$q,$q,$size,$offset]);return['items'=>array_map(fn($x)=>$this->camel($x),$rows),'page'=>$page,'pageSize'=>$size,'total'=>$total,'pages'=>(int)ceil($total/$size)];}
 public function prnRows(string$where='1=1',array$args=[]):array{$rows=$this->db->all("SELECT p.*,d.number delivery_number,v.id vehicle_id,v.number vehicle_number,(SELECT COUNT(*) FROM prn_items i WHERE i.prn_id=p.id AND i.deleted_at IS NULL) sku_count,COALESCE((SELECT SUM(i.planned) FROM prn_items i WHERE i.prn_id=p.id AND i.deleted_at IS NULL),0) planned,COALESCE((SELECT SUM(i.received) FROM prn_items i WHERE i.prn_id=p.id AND i.deleted_at IS NULL),0) received,COALESCE((SELECT SUM(x.quantity) FROM placements x WHERE x.prn_id=p.id),0) placed FROM prns p JOIN deliveries d ON d.id=p.delivery_id LEFT JOIN vehicles v ON v.id=d.vehicle_id WHERE p.deleted_at IS NULL AND $where ORDER BY p.created_at DESC",$args);return array_map(fn($x)=>$this->prnView($x),$rows);}
 public function prnView(array$r):array{$items=(int)$r['sku_count'];$received=(int)$r['received'];$planned=(int)$r['planned'];$placed=(int)$r['placed'];$status=!$items?'Создан':(!$r['reception_started_at']?'Товары загружены':($r['ready_at']?($placed>0?($placed>=$received?'Размещён':'Размещается'):'Готов к размещению'):($received>=$planned?'Приёмка завершена':'Приёмка')));if($r['closed_at'])$status='Закрыт';$r['status']=$status;return$this->camel($r);}
}
